#############################################################################
# Makefile for building: systemd-manage
# Generated by qmake (3.1) (Qt 5.15.14)
# Project:  systemd-manage.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile systemd-manage.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I. -I/../lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = systemd-manage1.0
DISTDIR = /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/.tmp/systemd-manage1.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lsystemd /usr/lib64/libQt5Svg.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5DBus.so /usr/lib64/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/aboutwindow.cpp \
		src/boottimes.cpp \
		src/configfile.cpp \
		src/configfilewindow.cpp \
		src/customcanttchartscene.cpp \
		src/customcanttchartview.cpp \
		src/customcantttimebaritem.cpp \
		src/customlistwidgetitem.cpp \
		src/customsortfilterproxymodel.cpp \
		src/customsvggraphicsview.cpp \
		src/highlighter.cpp \
		src/journalwindow.cpp \
		src/main.cpp \
		src/mainwidget.cpp \
		src/mystyleditemdelegate.cpp \
		src/qprocessinfo.cpp \
		src/qprocessinfowindow.cpp \
		src/settingswindow.cpp \
		src/systemdjournalinterface.cpp \
		src/systemdmanagerinterface.cpp \
		src/unitinformation.cpp \
		src/unitwindow.cpp \
		src/usersessionwindow.cpp \
		src/systemdgeneric.cpp \
		src/unitmodel.cpp \
		src/usersessioninformation.cpp \
		src/configfileinformation.cpp \
		src/analyzewindow.cpp qrc_resources.cpp \
		moc_aboutwindow.cpp \
		moc_configfilewindow.cpp \
		moc_customcanttchartscene.cpp \
		moc_customcanttchartview.cpp \
		moc_customlistwidgetitem.cpp \
		moc_customsortfilterproxymodel.cpp \
		moc_highlighter.cpp \
		moc_journalwindow.cpp \
		moc_mainwidget.cpp \
		moc_mystyleditemdelegate.cpp \
		moc_qprocessinfowindow.cpp \
		moc_settingswindow.cpp \
		moc_unitinformation.cpp \
		moc_unitwindow.cpp \
		moc_usersessionwindow.cpp \
		moc_unitmodel.cpp \
		moc_configfileinformation.cpp \
		moc_usersessioninformation.cpp \
		moc_analyzewindow.cpp
OBJECTS       = aboutwindow.o \
		boottimes.o \
		configfile.o \
		configfilewindow.o \
		customcanttchartscene.o \
		customcanttchartview.o \
		customcantttimebaritem.o \
		customlistwidgetitem.o \
		customsortfilterproxymodel.o \
		customsvggraphicsview.o \
		highlighter.o \
		journalwindow.o \
		main.o \
		mainwidget.o \
		mystyleditemdelegate.o \
		qprocessinfo.o \
		qprocessinfowindow.o \
		settingswindow.o \
		systemdjournalinterface.o \
		systemdmanagerinterface.o \
		unitinformation.o \
		unitwindow.o \
		usersessionwindow.o \
		systemdgeneric.o \
		unitmodel.o \
		usersessioninformation.o \
		configfileinformation.o \
		analyzewindow.o \
		qrc_resources.o \
		moc_aboutwindow.o \
		moc_configfilewindow.o \
		moc_customcanttchartscene.o \
		moc_customcanttchartview.o \
		moc_customlistwidgetitem.o \
		moc_customsortfilterproxymodel.o \
		moc_highlighter.o \
		moc_journalwindow.o \
		moc_mainwidget.o \
		moc_mystyleditemdelegate.o \
		moc_qprocessinfowindow.o \
		moc_settingswindow.o \
		moc_unitinformation.o \
		moc_unitwindow.o \
		moc_usersessionwindow.o \
		moc_unitmodel.o \
		moc_configfileinformation.o \
		moc_usersessioninformation.o \
		moc_analyzewindow.o
DIST          = /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/../lib64/qt5/mkspecs/modules/qt_KAuthCore.pri \
		/../lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/../lib64/qt5/mkspecs/modules/qt_KCrash.pri \
		/../lib64/qt5/mkspecs/modules/qt_KI18n.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/dbuscommon.pri \
		/../lib64/qt5/mkspecs/features/dbusinterfaces.prf \
		/../lib64/qt5/mkspecs/features/dbusadaptors.prf \
		/../lib64/qt5/mkspecs/features/unix/opengl.prf \
		/../lib64/qt5/mkspecs/features/uic.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		systemd-manage.pro src/aboutwindow.h \
		src/boottimes.h \
		src/configfile.h \
		src/configfilewindow.h \
		src/customcanttchartscene.h \
		src/customcanttchartview.h \
		src/customcantttimebaritem.h \
		src/customlistwidgetitem.h \
		src/customsortfilterproxymodel.h \
		src/customsvggraphicsview.h \
		src/globalvar.h \
		src/highlighter.h \
		src/journalwindow.h \
		src/mainwidget.h \
		src/mystyleditemdelegate.h \
		src/qprocessinfo.h \
		src/qprocessinfowindow.h \
		src/settingswindow.h \
		src/systemdjournalinterface.h \
		src/systemdmanagerinterface.h \
		src/unitinformation.h \
		src/unitwindow.h \
		src/usersessionwindow.h \
		src/unitmodel.h \
		src/systemdgeneric.h \
		src/configfileinformation.h \
		src/usersessioninformation.h \
		src/analyzewindow.h \
		src/version.h src/aboutwindow.cpp \
		src/boottimes.cpp \
		src/configfile.cpp \
		src/configfilewindow.cpp \
		src/customcanttchartscene.cpp \
		src/customcanttchartview.cpp \
		src/customcantttimebaritem.cpp \
		src/customlistwidgetitem.cpp \
		src/customsortfilterproxymodel.cpp \
		src/customsvggraphicsview.cpp \
		src/highlighter.cpp \
		src/journalwindow.cpp \
		src/main.cpp \
		src/mainwidget.cpp \
		src/mystyleditemdelegate.cpp \
		src/qprocessinfo.cpp \
		src/qprocessinfowindow.cpp \
		src/settingswindow.cpp \
		src/systemdjournalinterface.cpp \
		src/systemdmanagerinterface.cpp \
		src/unitinformation.cpp \
		src/unitwindow.cpp \
		src/usersessionwindow.cpp \
		src/systemdgeneric.cpp \
		src/unitmodel.cpp \
		src/usersessioninformation.cpp \
		src/configfileinformation.cpp \
		src/analyzewindow.cpp
QMAKE_TARGET  = systemd-manage
DESTDIR       = 
TARGET        = systemd-manage


first: all
####### Build rules

systemd-manage:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: systemd-manage.pro /../lib64/qt5/mkspecs/linux-g++/qmake.conf /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/../lib64/qt5/mkspecs/modules/qt_KAuthCore.pri \
		/../lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/../lib64/qt5/mkspecs/modules/qt_KCrash.pri \
		/../lib64/qt5/mkspecs/modules/qt_KI18n.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/dbuscommon.pri \
		/../lib64/qt5/mkspecs/features/dbusinterfaces.prf \
		/../lib64/qt5/mkspecs/features/dbusadaptors.prf \
		/../lib64/qt5/mkspecs/features/unix/opengl.prf \
		/../lib64/qt5/mkspecs/features/uic.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		systemd-manage.pro \
		res/resources.qrc
	$(QMAKE) -o Makefile systemd-manage.pro
/../lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/../lib64/qt5/mkspecs/qconfig.pri:
/../lib64/qt5/mkspecs/modules/qt_KAuth.pri:
/../lib64/qt5/mkspecs/modules/qt_KAuthCore.pri:
/../lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/../lib64/qt5/mkspecs/modules/qt_KCrash.pri:
/../lib64/qt5/mkspecs/modules/qt_KI18n.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_pdf.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_pdf_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_repparser.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_scxml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webengine.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webview.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/../lib64/qt5/mkspecs/features/qt_functions.prf:
/../lib64/qt5/mkspecs/features/qt_config.prf:
/../lib64/qt5/mkspecs/linux-g++/qmake.conf:
/../lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/../lib64/qt5/mkspecs/features/exclusive_builds.prf:
/../lib64/qt5/mkspecs/features/toolchain.prf:
/../lib64/qt5/mkspecs/features/default_pre.prf:
/../lib64/qt5/mkspecs/features/resolve_config.prf:
/../lib64/qt5/mkspecs/features/default_post.prf:
/../lib64/qt5/mkspecs/features/warn_on.prf:
/../lib64/qt5/mkspecs/features/qt.prf:
/../lib64/qt5/mkspecs/features/resources_functions.prf:
/../lib64/qt5/mkspecs/features/resources.prf:
/../lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/dbuscommon.pri:
/../lib64/qt5/mkspecs/features/dbusinterfaces.prf:
/../lib64/qt5/mkspecs/features/dbusadaptors.prf:
/../lib64/qt5/mkspecs/features/unix/opengl.prf:
/../lib64/qt5/mkspecs/features/uic.prf:
/../lib64/qt5/mkspecs/features/unix/thread.prf:
/../lib64/qt5/mkspecs/features/qmake_use.prf:
/../lib64/qt5/mkspecs/features/file_copies.prf:
/../lib64/qt5/mkspecs/features/testcase_targets.prf:
/../lib64/qt5/mkspecs/features/exceptions.prf:
/../lib64/qt5/mkspecs/features/yacc.prf:
/../lib64/qt5/mkspecs/features/lex.prf:
systemd-manage.pro:
res/resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile systemd-manage.pro

qmake_all: FORCE


all: Makefile systemd-manage

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /../lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/aboutwindow.h src/boottimes.h src/configfile.h src/configfilewindow.h src/customcanttchartscene.h src/customcanttchartview.h src/customcantttimebaritem.h src/customlistwidgetitem.h src/customsortfilterproxymodel.h src/customsvggraphicsview.h src/globalvar.h src/highlighter.h src/journalwindow.h src/mainwidget.h src/mystyleditemdelegate.h src/qprocessinfo.h src/qprocessinfowindow.h src/settingswindow.h src/systemdjournalinterface.h src/systemdmanagerinterface.h src/unitinformation.h src/unitwindow.h src/usersessionwindow.h src/unitmodel.h src/systemdgeneric.h src/configfileinformation.h src/usersessioninformation.h src/analyzewindow.h src/version.h $(DISTDIR)/
	$(COPY_FILE) --parents src/aboutwindow.cpp src/boottimes.cpp src/configfile.cpp src/configfilewindow.cpp src/customcanttchartscene.cpp src/customcanttchartview.cpp src/customcantttimebaritem.cpp src/customlistwidgetitem.cpp src/customsortfilterproxymodel.cpp src/customsvggraphicsview.cpp src/highlighter.cpp src/journalwindow.cpp src/main.cpp src/mainwidget.cpp src/mystyleditemdelegate.cpp src/qprocessinfo.cpp src/qprocessinfowindow.cpp src/settingswindow.cpp src/systemdjournalinterface.cpp src/systemdmanagerinterface.cpp src/unitinformation.cpp src/unitwindow.cpp src/usersessionwindow.cpp src/systemdgeneric.cpp src/unitmodel.cpp src/usersessioninformation.cpp src/configfileinformation.cpp src/analyzewindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents res/translators/app_zh_CN.ts res/translators/app_en_US.ts res/translators/app_de_DE.ts res/translators/app_ru_RU.ts res/translators/app_fr_FR.ts res/translators/app_ja_JP.ts res/translators/app_zh_TW.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: res/resources.qrc \
		/../lib64/qt5/bin/rcc \
		res/translators/app_ru_RU.qm \
		res/translators/app_de_DE.qm \
		res/translators/app_zh_CN.qm \
		res/translators/app_fr_FR.qm \
		res/translators/app_ja_JP.qm \
		res/translators/app_en_US.qm \
		res/translators/app_zh_TW.qm \
		res/icons/emblem-unavailable.svg \
		res/icons/version-info.svg \
		res/icons/emblem-pause.svg \
		res/icons/process-manage.svg \
		res/icons/systemd-service.svg \
		res/icons/emblem-unreadable.svg \
		res/icons/system-setting.svg \
		res/icons/emblem-error.svg \
		res/icons/systemd-manage.png \
		res/icons/version-info-blk.svg \
		res/icons/analysize-statistics.svg \
		res/icons/systemd-manage.ico \
		res/icons/down-arrow-16.svg \
		res/icons/emblem-success.svg \
		res/icons/config-file.svg \
		res/icons/journal-log.svg \
		res/icons/user-session.svg \
		res/icons/systemd-unit.svg \
		res/icons/emblem-system.svg \
		res/icons/emblem-default.svg
	/../lib64/qt5/bin/rcc -name resources res/resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /../lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /../lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_aboutwindow.cpp moc_configfilewindow.cpp moc_customcanttchartscene.cpp moc_customcanttchartview.cpp moc_customlistwidgetitem.cpp moc_customsortfilterproxymodel.cpp moc_highlighter.cpp moc_journalwindow.cpp moc_mainwidget.cpp moc_mystyleditemdelegate.cpp moc_qprocessinfowindow.cpp moc_settingswindow.cpp moc_unitinformation.cpp moc_unitwindow.cpp moc_usersessionwindow.cpp moc_unitmodel.cpp moc_configfileinformation.cpp moc_usersessioninformation.cpp moc_analyzewindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aboutwindow.cpp moc_configfilewindow.cpp moc_customcanttchartscene.cpp moc_customcanttchartview.cpp moc_customlistwidgetitem.cpp moc_customsortfilterproxymodel.cpp moc_highlighter.cpp moc_journalwindow.cpp moc_mainwidget.cpp moc_mystyleditemdelegate.cpp moc_qprocessinfowindow.cpp moc_settingswindow.cpp moc_unitinformation.cpp moc_unitwindow.cpp moc_usersessionwindow.cpp moc_unitmodel.cpp moc_configfileinformation.cpp moc_usersessioninformation.cpp moc_analyzewindow.cpp
moc_aboutwindow.cpp: src/aboutwindow.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/aboutwindow.h -o moc_aboutwindow.cpp

moc_configfilewindow.cpp: src/configfilewindow.h \
		src/systemdmanagerinterface.h \
		src/systemdgeneric.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/configfilewindow.h -o moc_configfilewindow.cpp

moc_customcanttchartscene.cpp: src/customcanttchartscene.h \
		src/customcantttimebaritem.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/customcanttchartscene.h -o moc_customcanttchartscene.cpp

moc_customcanttchartview.cpp: src/customcanttchartview.h \
		src/customcanttchartscene.h \
		src/customcantttimebaritem.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/customcanttchartview.h -o moc_customcanttchartview.cpp

moc_customlistwidgetitem.cpp: src/customlistwidgetitem.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/customlistwidgetitem.h -o moc_customlistwidgetitem.cpp

moc_customsortfilterproxymodel.cpp: src/customsortfilterproxymodel.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/customsortfilterproxymodel.h -o moc_customsortfilterproxymodel.cpp

moc_highlighter.cpp: src/highlighter.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/highlighter.h -o moc_highlighter.cpp

moc_journalwindow.cpp: src/journalwindow.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/journalwindow.h -o moc_journalwindow.cpp

moc_mainwidget.cpp: src/mainwidget.h \
		src/configfilewindow.h \
		src/systemdmanagerinterface.h \
		src/systemdgeneric.h \
		src/settingswindow.h \
		src/configfile.h \
		src/unitwindow.h \
		src/customsortfilterproxymodel.h \
		src/unitmodel.h \
		src/mystyleditemdelegate.h \
		src/usersessionwindow.h \
		src/analyzewindow.h \
		src/customsvggraphicsview.h \
		src/customcanttchartview.h \
		src/customcanttchartscene.h \
		src/customcantttimebaritem.h \
		src/boottimes.h \
		src/journalwindow.h \
		src/qprocessinfowindow.h \
		src/aboutwindow.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/mainwidget.h -o moc_mainwidget.cpp

moc_mystyleditemdelegate.cpp: src/mystyleditemdelegate.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/mystyleditemdelegate.h -o moc_mystyleditemdelegate.cpp

moc_qprocessinfowindow.cpp: src/qprocessinfowindow.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/qprocessinfowindow.h -o moc_qprocessinfowindow.cpp

moc_settingswindow.cpp: src/settingswindow.h \
		src/configfile.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/settingswindow.h -o moc_settingswindow.cpp

moc_unitinformation.cpp: src/unitinformation.h \
		src/systemdgeneric.h \
		src/unitmodel.h \
		src/systemdmanagerinterface.h \
		src/highlighter.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/unitinformation.h -o moc_unitinformation.cpp

moc_unitwindow.cpp: src/unitwindow.h \
		src/customsortfilterproxymodel.h \
		src/systemdgeneric.h \
		src/unitmodel.h \
		src/systemdmanagerinterface.h \
		src/mystyleditemdelegate.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/unitwindow.h -o moc_unitwindow.cpp

moc_usersessionwindow.cpp: src/usersessionwindow.h \
		src/systemdgeneric.h \
		src/systemdmanagerinterface.h \
		src/mystyleditemdelegate.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/usersessionwindow.h -o moc_usersessionwindow.cpp

moc_unitmodel.cpp: src/unitmodel.h \
		src/systemdgeneric.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/unitmodel.h -o moc_unitmodel.cpp

moc_configfileinformation.cpp: src/configfileinformation.h \
		src/systemdmanagerinterface.h \
		src/systemdgeneric.h \
		src/highlighter.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/configfileinformation.h -o moc_configfileinformation.cpp

moc_usersessioninformation.cpp: src/usersessioninformation.h \
		src/systemdgeneric.h \
		src/systemdmanagerinterface.h \
		src/mystyleditemdelegate.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/usersessioninformation.h -o moc_usersessioninformation.cpp

moc_analyzewindow.cpp: src/analyzewindow.h \
		src/customsvggraphicsview.h \
		src/customcanttchartview.h \
		src/customcanttchartscene.h \
		src/customcantttimebaritem.h \
		src/boottimes.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0 -I/home/han/qt-dev-projects/systemd-manager-tools-qt-develop-mywork-2024-latest/systemd-manage-v1.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/14 -I/usr/include/c++/14/x86_64-redhat-linux -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-redhat-linux/14/include -I/usr/local/include -I/usr/include src/analyzewindow.h -o moc_analyzewindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

aboutwindow.o: src/aboutwindow.cpp src/aboutwindow.h \
		src/version.h \
		src/customlistwidgetitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutwindow.o src/aboutwindow.cpp

boottimes.o: src/boottimes.cpp src/boottimes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boottimes.o src/boottimes.cpp

configfile.o: src/configfile.cpp src/configfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configfile.o src/configfile.cpp

configfilewindow.o: src/configfilewindow.cpp src/configfilewindow.h \
		src/systemdmanagerinterface.h \
		src/systemdgeneric.h \
		src/configfileinformation.h \
		src/highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configfilewindow.o src/configfilewindow.cpp

customcanttchartscene.o: src/customcanttchartscene.cpp src/customcanttchartscene.h \
		src/customcantttimebaritem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customcanttchartscene.o src/customcanttchartscene.cpp

customcanttchartview.o: src/customcanttchartview.cpp src/customcanttchartview.h \
		src/customcanttchartscene.h \
		src/customcantttimebaritem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customcanttchartview.o src/customcanttchartview.cpp

customcantttimebaritem.o: src/customcantttimebaritem.cpp src/customcantttimebaritem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customcantttimebaritem.o src/customcantttimebaritem.cpp

customlistwidgetitem.o: src/customlistwidgetitem.cpp src/customlistwidgetitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customlistwidgetitem.o src/customlistwidgetitem.cpp

customsortfilterproxymodel.o: src/customsortfilterproxymodel.cpp src/customsortfilterproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customsortfilterproxymodel.o src/customsortfilterproxymodel.cpp

customsvggraphicsview.o: src/customsvggraphicsview.cpp src/customsvggraphicsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customsvggraphicsview.o src/customsvggraphicsview.cpp

highlighter.o: src/highlighter.cpp src/highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highlighter.o src/highlighter.cpp

journalwindow.o: src/journalwindow.cpp src/journalwindow.h \
		src/systemdjournalinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o journalwindow.o src/journalwindow.cpp

main.o: src/main.cpp src/mainwidget.h \
		src/configfilewindow.h \
		src/systemdmanagerinterface.h \
		src/systemdgeneric.h \
		src/settingswindow.h \
		src/configfile.h \
		src/unitwindow.h \
		src/customsortfilterproxymodel.h \
		src/unitmodel.h \
		src/mystyleditemdelegate.h \
		src/usersessionwindow.h \
		src/analyzewindow.h \
		src/customsvggraphicsview.h \
		src/customcanttchartview.h \
		src/customcanttchartscene.h \
		src/customcantttimebaritem.h \
		src/boottimes.h \
		src/journalwindow.h \
		src/qprocessinfowindow.h \
		src/aboutwindow.h \
		src/globalvar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwidget.o: src/mainwidget.cpp src/mainwidget.h \
		src/configfilewindow.h \
		src/systemdmanagerinterface.h \
		src/systemdgeneric.h \
		src/settingswindow.h \
		src/configfile.h \
		src/unitwindow.h \
		src/customsortfilterproxymodel.h \
		src/unitmodel.h \
		src/mystyleditemdelegate.h \
		src/usersessionwindow.h \
		src/analyzewindow.h \
		src/customsvggraphicsview.h \
		src/customcanttchartview.h \
		src/customcanttchartscene.h \
		src/customcantttimebaritem.h \
		src/boottimes.h \
		src/journalwindow.h \
		src/qprocessinfowindow.h \
		src/aboutwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o src/mainwidget.cpp

mystyleditemdelegate.o: src/mystyleditemdelegate.cpp src/mystyleditemdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mystyleditemdelegate.o src/mystyleditemdelegate.cpp

qprocessinfo.o: src/qprocessinfo.cpp src/qprocessinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qprocessinfo.o src/qprocessinfo.cpp

qprocessinfowindow.o: src/qprocessinfowindow.cpp src/qprocessinfowindow.h \
		src/qprocessinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qprocessinfowindow.o src/qprocessinfowindow.cpp

settingswindow.o: src/settingswindow.cpp src/settingswindow.h \
		src/configfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingswindow.o src/settingswindow.cpp

systemdjournalinterface.o: src/systemdjournalinterface.cpp src/systemdjournalinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemdjournalinterface.o src/systemdjournalinterface.cpp

systemdmanagerinterface.o: src/systemdmanagerinterface.cpp src/systemdmanagerinterface.h \
		src/systemdgeneric.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemdmanagerinterface.o src/systemdmanagerinterface.cpp

unitinformation.o: src/unitinformation.cpp src/unitinformation.h \
		src/systemdgeneric.h \
		src/unitmodel.h \
		src/systemdmanagerinterface.h \
		src/highlighter.h \
		src/systemdjournalinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unitinformation.o src/unitinformation.cpp

unitwindow.o: src/unitwindow.cpp src/unitwindow.h \
		src/customsortfilterproxymodel.h \
		src/systemdgeneric.h \
		src/unitmodel.h \
		src/systemdmanagerinterface.h \
		src/mystyleditemdelegate.h \
		src/unitinformation.h \
		src/highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unitwindow.o src/unitwindow.cpp

usersessionwindow.o: src/usersessionwindow.cpp src/usersessionwindow.h \
		src/systemdgeneric.h \
		src/systemdmanagerinterface.h \
		src/mystyleditemdelegate.h \
		src/usersessioninformation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usersessionwindow.o src/usersessionwindow.cpp

systemdgeneric.o: src/systemdgeneric.cpp src/systemdgeneric.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemdgeneric.o src/systemdgeneric.cpp

unitmodel.o: src/unitmodel.cpp src/unitmodel.h \
		src/systemdgeneric.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unitmodel.o src/unitmodel.cpp

usersessioninformation.o: src/usersessioninformation.cpp src/usersessioninformation.h \
		src/systemdgeneric.h \
		src/systemdmanagerinterface.h \
		src/mystyleditemdelegate.h \
		src/customlistwidgetitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usersessioninformation.o src/usersessioninformation.cpp

configfileinformation.o: src/configfileinformation.cpp src/configfileinformation.h \
		src/systemdmanagerinterface.h \
		src/systemdgeneric.h \
		src/highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configfileinformation.o src/configfileinformation.cpp

analyzewindow.o: src/analyzewindow.cpp src/analyzewindow.h \
		src/customsvggraphicsview.h \
		src/customcanttchartview.h \
		src/customcanttchartscene.h \
		src/customcantttimebaritem.h \
		src/boottimes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analyzewindow.o src/analyzewindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_aboutwindow.o: moc_aboutwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutwindow.o moc_aboutwindow.cpp

moc_configfilewindow.o: moc_configfilewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configfilewindow.o moc_configfilewindow.cpp

moc_customcanttchartscene.o: moc_customcanttchartscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customcanttchartscene.o moc_customcanttchartscene.cpp

moc_customcanttchartview.o: moc_customcanttchartview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customcanttchartview.o moc_customcanttchartview.cpp

moc_customlistwidgetitem.o: moc_customlistwidgetitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customlistwidgetitem.o moc_customlistwidgetitem.cpp

moc_customsortfilterproxymodel.o: moc_customsortfilterproxymodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customsortfilterproxymodel.o moc_customsortfilterproxymodel.cpp

moc_highlighter.o: moc_highlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_highlighter.o moc_highlighter.cpp

moc_journalwindow.o: moc_journalwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_journalwindow.o moc_journalwindow.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_mystyleditemdelegate.o: moc_mystyleditemdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mystyleditemdelegate.o moc_mystyleditemdelegate.cpp

moc_qprocessinfowindow.o: moc_qprocessinfowindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qprocessinfowindow.o moc_qprocessinfowindow.cpp

moc_settingswindow.o: moc_settingswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingswindow.o moc_settingswindow.cpp

moc_unitinformation.o: moc_unitinformation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_unitinformation.o moc_unitinformation.cpp

moc_unitwindow.o: moc_unitwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_unitwindow.o moc_unitwindow.cpp

moc_usersessionwindow.o: moc_usersessionwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usersessionwindow.o moc_usersessionwindow.cpp

moc_unitmodel.o: moc_unitmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_unitmodel.o moc_unitmodel.cpp

moc_configfileinformation.o: moc_configfileinformation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configfileinformation.o moc_configfileinformation.cpp

moc_usersessioninformation.o: moc_usersessioninformation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usersessioninformation.o moc_usersessioninformation.cpp

moc_analyzewindow.o: moc_analyzewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_analyzewindow.o moc_analyzewindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/systemd-manage/bin || mkdir -p $(INSTALL_ROOT)/opt/systemd-manage/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/systemd-manage/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/systemd-manage/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/systemd-manage/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/systemd-manage/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

