name: build

on: [push, pull_request]

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  BUILD_CONFIGURATION: Release
jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Qt dependencies
        run: >
          sudo apt-get  update -y &&
          sudo apt-get  install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools g++  libqt5svg5-dev libqt5charts5  && 
          sudo apt-get  install -y make  libglib2.0-dev  libgtop2-dev   pkg-config libsystemd-dev libudev-dev
      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build
      - name: Configure Qmake
        run: qmake
      - name: make
        run: make -j
